const screens=document.querySelectorAll(".screen");
let currentMode="host";
let currentLobbyCode="";
let players=[];

function showScreen(id){screens.forEach(s=>s.classList.remove("active"));const target=document.getElementById(id);if(target)target.classList.add("active");window.scrollTo({top:0,behavior:"smooth"});}
function generateLobbyCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let code="";for(let i=0;i<6;i++)code+=chars[Math.floor(Math.random()*chars.length)];return code;}
function getJoinLink(code){const base=window.location.origin+window.location.pathname;return base.replace(/\/$/,"")+"?join="+code;}
function renderPlayers(){const lists=[document.getElementById("host-player-list"),document.getElementById("player-list")];lists.forEach(list=>{if(!list)return;list.innerHTML="";if(players.length===0){list.innerHTML='<p class="empty-state">No players have joined yet.</p>';return;}players.forEach(player=>{const row=document.createElement("div");row.className="player-row";row.innerHTML='<span class="player-name"></span><span class="player-badge"></span>';row.querySelector(".player-name").textContent=player.name;row.querySelector(".player-badge").textContent=player.host?"HOST":"PLAYER";list.appendChild(row);});});document.getElementById("host-player-count").textContent=players.length;document.getElementById("player-count").textContent=players.length;}
function createLobby(mode){currentMode=mode;currentLobbyCode=generateLobbyCode();players=[];if(mode==="host-player")players.push({name:"Host Player",host:true});document.getElementById("lobby-code").textContent=currentLobbyCode;document.getElementById("join-link").value=getJoinLink(currentLobbyCode);document.getElementById("host-status").textContent=mode==="host-player"?"Host + Player device is ready.":"Waiting for players...";renderPlayers();const qr=document.getElementById("qr-code");qr.innerHTML="";if(typeof QRCode!=="undefined"){new QRCode(qr,{text:getJoinLink(currentLobbyCode),width:170,height:170,colorDark:"#111111",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M});}else qr.innerHTML="<span>QR</span>";showScreen("host-screen");}
function enterLobby(){document.getElementById("lobby-display-code").textContent=currentLobbyCode;document.getElementById("lobby-mode-text").textContent=currentMode==="host-player"?"Host + Player mode":currentMode==="host"?"Host mode":"Player mode";renderPlayers();showScreen("lobby-screen");}
document.getElementById("create-lobby-btn").addEventListener("click",()=>showScreen("mode-screen"));
document.getElementById("join-lobby-btn").addEventListener("click",()=>{document.getElementById("lobby-code-input").value="";document.getElementById("player-name-input").value="";document.getElementById("join-error").textContent="";showScreen("join-screen");});
document.querySelectorAll(".mode-card").forEach(button=>button.addEventListener("click",()=>createLobby(button.dataset.mode)));
document.querySelectorAll("[data-back]").forEach(button=>button.addEventListener("click",()=>showScreen(button.dataset.back)));
document.getElementById("copy-link-btn").addEventListener("click",async()=>{const input=document.getElementById("join-link");try{await navigator.clipboard.writeText(input.value);document.getElementById("copy-link-btn").textContent="Copied!";setTimeout(()=>document.getElementById("copy-link-btn").textContent="Copy",1400);}catch{input.select();document.execCommand("copy");}});
document.getElementById("enter-host-lobby-btn").addEventListener("click",enterLobby);
document.getElementById("join-form").addEventListener("submit",event=>{event.preventDefault();const code=document.getElementById("lobby-code-input").value.trim().toUpperCase();const name=document.getElementById("player-name-input").value.trim();const error=document.getElementById("join-error");if(!/^[A-Z0-9]{6}$/.test(code)){error.textContent="Enter a valid 6-character lobby code.";return;}if(!name){error.textContent="Enter a player name.";return;}if(name.length>20){error.textContent="Player names can be up to 20 characters.";return;}error.textContent="";currentLobbyCode=code;currentMode="player";players=[{name,host:false}];document.getElementById("lobby-display-code").textContent=code;document.getElementById("lobby-mode-text").textContent="Player mode";renderPlayers();showScreen("lobby-screen");});
const params=new URLSearchParams(window.location.search);const joinCode=params.get("join");if(joinCode){document.getElementById("lobby-code-input").value=joinCode.toUpperCase();showScreen("join-screen");}